  # Overview :
  ## 1. Intro to the course
  - Data Science course - General 
  - Python for Data Science
## 2. Why to use a notebook
- Easy to use
  ## 3. How to use a notebook
- Create one
- Set name 
- Create a cell - Text / Code
- Run - A cell / All cells
- Move -Up_down / Delete
- Save / Download


Prohobited python variable names

In [1]:
a = 2 
b = 3 
a/b

0.6666666666666666

In [2]:
a = 4

In [3]:
b = 3 

# Session 1 :Python for Data Science
Let's get started 

- Data types / Assign a value

# Simple Data types in Python
- int
- float
- String

In [4]:
## Assign a value
a = 3 ## integer
b = 3.3 ## float
a

3

In [6]:
a

3

In [7]:
a = 20
a

20

In [8]:
a = 3.7
a

3.7

In [9]:
a = 'a'
b = 'I am a Pythoneer'
c = 'Python' ## String

In [10]:
b

'I am a Pythoneer'

In [16]:
b[-1]

'r'

In [17]:
c[0]='p'
## String are immutable

TypeError: ignored

In [18]:
c = 'Java'
c

'Java'

In [20]:
d = c*3 + b
d

'JavaJavaJavaI am a Pythoneer'

In [ ]:
b

22

In [ ]:
b = 'Data Science'

# Inputs / Outputs

Inputs

In [21]:
num = input('Enter a number between 0 and 100 : ')

Enter a number between 0 and 100 : 93


In [22]:
num

'93'

In [23]:
3

3

In [26]:
'I am a programmer'

'I am a programmer'

In [27]:
num = int(input("Enter number :"))

Enter number :60


In [28]:
num

60

In [ ]:
num = float(input("Enter number :"))

Enter number :33


In [ ]:
num

33.0

In [29]:
x, y = input("Enter two values: ").split()

Enter two values: 177 122


In [33]:
x = int(x)
x

177

In [31]:
y

'122'

In [ ]:
x = int(input("Enter a number :"))
y = int(input("Enter a number :"))

Enter number :3
Enter number :4


In [ ]:
x

3

- Output

In [34]:
print('The course is helpful')

The course is helpful


In [38]:
print(x,'x',y,'Alexandria is beautiful')

177 x 122 Alexandria is beautiful


In [39]:
print('Cairo is a beautiful City,','so is Alexandria','3','6',x)

Cairo is a beautiful City, so is Alexandria 3 6 177


# Operators in Python

Operators : + - * / // ** %

In [42]:
11%8

3

In [43]:
x,y,z,l,m = 3,2,3,5,1

In [44]:
l

5

In [45]:
x + y 

5

In [46]:
x - y 

1

In [47]:
x * y 

6

In [48]:
x / y 

1.5

In [49]:
x // y

1

In [50]:
x ** y 

9

In [51]:
x%y

1

# Control Flow
 - Loops
 - For loops

 For loops, in general, are used for sequential traversal. It falls under the category of definite iteration. Definite iterations means the number of repetitions is specified explicitly in advance. 
Note: In python, for loops only implements the collection-based iteration.

In [60]:
print('1 2 3')

1 2 3


In [61]:
print('1 2 3 4 5 6 7 8 9 10')

1 2 3 4 5 6 7 8 9 10


In [63]:
for counter in range(1,51):
  print(counter)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50


In [66]:
for i in 'Python code':
  print(i)

P
y
t
h
o
n
 
c
o
d
e


- While loops
In Python, While Loops is used to execute a block of statements repeatedly until a given condition is satisfied. And when the condition becomes false, the line immediately after the loop in the program is executed. While loop falls under the category of indefinite iteration. Indefinite iteration means that the number of times the loop is executed isn’t specified explicitly in advance.



In [67]:
count = 0
while (count < 3):      
    count = count + 1
    print("Hello Pythoneer/Pythonista")

Hello Pythoneer/Pythonista
Hello Pythoneer/Pythonista
Hello Pythoneer/Pythonista


In [73]:
count = 2
while (count < 3):
  count = count + 1
  print('Hello')

Hello


- Conditions

In [75]:
i = 10
if (i < 15): 
   print(i,"is less than 15")
   print("1")
   print("Do not play") 

10 is less than 15
1
Do not play


In [80]:
i = 15
if (i < 15): 
  print("i is less than 15")
elif (i == 15):
  print('i equals to 15')
elif (i > 15):
  print('i bigger than 15')

i equals to 15


In [82]:
i = 100
if (i == 15): 
  print("i is bigger than 15")
else:
  print('i equals to 15')

i equals to 15


# Data Structures
- Lists

List in Python are ordered and have a definite count. The elements in a list are indexed according to a definite sequence and the indexing of a list is done with 0 being the first index. Each element in the list has its definite place in the list, which allows duplicating of elements in the list, with each element having its own distinct place and credibility.



In [84]:
## Can contain numbers, characters or strings...
## How to define it 
L = [1,2.2, "a" , "string" , 1+2,'I am a Python programmer',1,'a'] 
L

[1, 2.2, 'a', 'string', 3, 'I am a Python programmer', 1, 'a']

In [87]:
## Order of elements:
L[-1]

'a'

In [ ]:
L[-1]

3

In [ ]:
L[1]

'a'

In [88]:
L[1] = 2
## Lists are immutable

In [89]:
L

[1, 2, 'a', 'string', 3, 'I am a Python programmer', 1, 'a']

In [91]:
L.append('Pythonista')

In [92]:
L

[1, 2, 'a', 'string', 3, 'I am a Python programmer', 1, 'a', 'Pythonista']

In [93]:
L.append(1)

In [94]:
L

[1, 2, 'a', 'string', 3, 'I am a Python programmer', 1, 'a', 'Pythonista', 1]

In [96]:
L.remove(1)
L

['a', 'string', 3, 'I am a Python programmer', 1, 'a', 'Pythonista', 1]

In [98]:
S = 'I am a future data scientist 55'
L = S.split(' ')
L

['I', 'am', 'a', 'future', 'data', 'scientist', '55']

- Tuples

Tuple is a collection of Python objects much like a list. The sequence of values stored in a tuple can be of any type, and they are indexed by integers.
Values of a tuple are syntactically separated by ‘commas’. Although it is not necessary, it is more common to define a tuple by closing the sequence of values in parentheses. This helps in understanding the Python tuples more easily.

In [100]:
## Can contain numbers, characters or strings...
## How to define it 
tup = (1,2,3,'a','Programmer')

In [105]:
tup[-1]
## tuples are mutable

'Programmer'

- Sets

In Python, Set is an unordered collection of data type that is iterable, mutable and has no duplicate elements. The order of elements in a set is undefined though it may consist of various elements.
The major advantage of using a set, as opposed to a list, is that it has a highly optimized method for checking whether a specific element is contained in the set.

In [108]:
set1 = set("Py3    Python") 
set1

{' ', '3', 'P', 'h', 'n', 'o', 't', 'y'}

In [119]:
A = ('a','3','3','b')
set2 = set(A)
set2

{'3', 'a', 'b'}

In [120]:
set2.add('to be')

In [121]:
set2

{'3', 'a', 'b', 'to be'}

In [122]:
set2.remove('3')
set2

{'a', 'b', 'to be'}

- Dictionary

Dictionary in Python is an unordered collection of data values, used to store data values like a map, which unlike other Data Types that hold only single value as an element, Dictionary holds key:value pair. Key value is provided in the dictionary to make it more optimized.

In [123]:
dict1 = {'Je':'I',
         'Tu':'You',
         'Il':'He'}
dict1['Je']

'I'

In [126]:
dict1['Avoir'] = 'To have'
dict1['Avoir']

'To have'

In [127]:
dict1

{'Avoir': 'To have', 'Il': 'He', 'Je': 'I', 'Tu': 'You'}

In [ ]:
del dict1['Tu']
dict1

In [125]:
dict2['Ahmed']

20

In [124]:
dict2 = {'Ahmed' : 20,
         'Seham' : 50,  
}

- Numpy 

Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.
Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data

- Arrays

Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy, number of dimensions of the array is called rank of the array.A tuple of integers giving the size of the array along each dimension is known as shape of the array. An array class in Numpy is called as ndarray. Elements in Numpy arrays are accessed by using square brackets and can be initialized by using nested Python Lists.



In [129]:
import numpy as np
# 1D-array
arr = np.array(   [1,2,23,5,6,3]
               )
print(arr)

[ 1  2 23  5  6  3]


In [131]:
arr[4]

6

In [132]:
# 2D-array
arr = np.array( [[-1, 2, 0, 4],
                 [4, -0.5, 6, 0],
                 [2.6, 0, 7, 8],
                 [3, -7, 4, 2.0]]
               )
print(arr)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [134]:
arr[3,2]

4.0

In [135]:
arr[1,0]

4.0

In [136]:
Trans_arr = arr.T
Trans_arr

array([[-1. ,  4. ,  2.6,  3. ],
       [ 2. , -0.5,  0. , -7. ],
       [ 0. ,  6. ,  7. ,  4. ],
       [ 4. ,  0. ,  8. ,  2. ]])

In [137]:
arr1= np.array([1,2,23])
arr2= np.array([[1],
                [2],
                [3]])
X = np.matmul(arr1,arr2)

In [138]:
X

array([74])

- Iteration and slicing

In [140]:
LIST = [1,2,3,'Saturday',5,6,8]
for element in LIST:
  print(element)

1
2
3
Saturday
5
6
8


In [141]:
arr1 = np.array([1,2,6])
for i in arr1:
  print(i)

1
2
6


In [142]:
for elem in set2:
  print(elem)

a
to be
b


In [149]:
LIST = [1,2,3,'Saturday',5,6,8]

LIST[2:]

[3, 'Saturday', 5, 6, 8]

In [151]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
arr[2:,:]

array([[ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])