# Overview
## Arrays - Slicing and indexing

## Numpy 

Numpy is a general-purpose array-processing package. It provides tools for working with these arrays. It is considered one of the fundamental packages for scientific computing with Python. Besides, Numpy can also be used as an efficient multi-dimensional container of generic data

- Arrays

Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy, number of dimensions of the array is called rank of the array.A tuple of integers giving the size of the array along each dimension is known as shape of the array. An array class in Numpy is called as ndarray. Elements in Numpy arrays are accessed by using square brackets.


In [ ]:
import numpy as np

# 1D-array
arr = np.array(  [1,2,23,5,2,3]  )
print(arr)  

[ 1  2 23  5  2  3]


In [ ]:
arr[-1]

3

In [ ]:
# 2D-array
arr = np.array( [ [-1, 2, 0, 4],
                 [4, -0.5, 6, 0],
                 [2.6, 0, 7, 8],
                 [3, -7, 4, 2.0] ] )
print(arr)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [ ]:
arr[1,1]

-0.5

In [ ]:
arr[2,2]

7.0

In [ ]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [ ]:
T_arr = arr.T
T_arr

array([[-1. ,  4. ,  2.6,  3. ],
       [ 2. , -0.5,  0. , -7. ],
       [ 0. ,  6. ,  7. ,  4. ],
       [ 4. ,  0. ,  8. ,  2. ]])

In [ ]:
## arr1:(1*4) ,  arr2:(4*1)
arr1 = np.array([1,2,23,2])
arr2 = np.array([[1],
                [2],
                [3],
                [4]])
X = np.matmul(arr1,arr2)

In [ ]:
X

array([82])

In [ ]:
a = np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]],[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]])
a

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]]])

- Iteration and slicing

In [ ]:
ListA = [ 1,'a','Data scientist',2.3,1]
ListA

[1, 'a', 'Data scientist', 2.3, 1]

In [ ]:
LIST = [1,2,3,'Saturday',5,6,8]
for z in LIST:
  print(z)

1
2
3
Saturday
5
6
8


In [ ]:
arr1 = np.array([1,2,6])
for i in arr1:
  print(i)

1
2
6


In [ ]:
set2 = {1,2,3,'a',2,'a' }

In [ ]:
set2

{1, 2, 3, 'a'}

In [ ]:
set2[0]

TypeError: ignored

In [ ]:
for elem in set2:
  print(elem,'a')

1 a
2 a
3 a
a a


In [ ]:
LIST = [1,2,3,'Saturday',5,6,8]

ListA = LIST[1:]
ListA

[2, 3, 'Saturday', 5, 6, 8]

In [ ]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
arr[1:3,1:3]

array([[-0.5,  6. ],
       [ 0. ,  7. ]])

Reference: 

> Book : Data science from scratch O'Reilly written by: Joel Grus - Page : 71
  
> Website : GeekforGeeks.com 
